level_1 typing exercises
DanTheMain/typing_challenges pull request #1
Opened 2023-09-08 10:09 UTC by DanTheMain

2023-09-10 23:41 UTC, vppuzakov requested changes
👍 почти везде аннотации проставлены верно
💡 обрати внимание на 8е упражение - надо поправить.

обязательно запускай `mypy`

2023-09-10 23:41 UTC, vppuzakov commented on level_1/1.py
> +def is_user_banned(user_id: int) -> bool:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/10.py
> +def stringify(value: str | int | float | None) -> str:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/2.py
> +def is_adult(age: int, country_name: str) -> bool:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/3.py
> +def compose_full_name(first_name: str, last_name: str, middle_name: Optional[str]) -> str:
👍 все верно
💡 в современном python можно использовать такой синтаксис `str | None` для указания опциональности

2023-09-10 23:41 UTC, vppuzakov commented on level_1/4.py
> +    assert calculate_age(date_of_birth=datetime.date(1965, 6, 2)) == 57 # nope
💡 для игнора используют `type: ignore[error-type]` - только лучше не злоупотреблять этим

2023-09-10 23:41 UTC, vppuzakov commented on level_1/4.py
> +def calculate_age(date_of_birth: datetime.date) -> int:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/5.py
> +def is_correct_email(raw_email: str) -> bool:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/6.py
> +def is_loan_amount_too_big(loan_amount_usd: int, max_loan_amount_for_user_usd: Optional[int]) -> bool:
👍 используй `int | None`

2023-09-10 23:41 UTC, vppuzakov commented on level_1/7.py
> +def send_email(header: str, text_content: str, send_to: str) -> None:
👍

2023-09-10 23:41 UTC, vppuzakov commented on level_1/8.py
> +def get_user_balance(user_id: uuid) -> decimal:
🔴  если запустишь `mypy level_1` - тут сработает ошибка - проанализируй ее и поправь аннотации

2023-09-10 23:41 UTC, vppuzakov commented on level_1/9.py
> +def is_correct_int(raw_int: Optional[str]) -> bool:
👍 используй `str | None`

2023-09-11 11:18 UTC, DanTheMain commented on level_1/3.py
> +def compose_full_name(first_name: str, last_name: str, middle_name: Optional[str]) -> str:
у меня был указан несколько несовременный питон (3.9); поправил, и удалил Optional сдесть и в других ихменениях

2023-09-11 11:19 UTC, DanTheMain commented on level_1/4.py
> +    assert calculate_age(date_of_birth=datetime.date(1965, 6, 2)) == 57 # nope
Это просто был мой комментарий на то что проверка не будет работать каждый год )

2023-09-11 11:19 UTC, DanTheMain commented on level_1/6.py
> +def is_loan_amount_too_big(loan_amount_usd: int, max_loan_amount_for_user_usd: Optional[int]) -> bool:
Done

2023-09-11 11:19 UTC, DanTheMain commented on level_1/8.py
> +def get_user_balance(user_id: uuid) -> decimal:
Поправил

2023-09-11 11:19 UTC, DanTheMain commented on level_1/9.py
> +def is_correct_int(raw_int: Optional[str]) -> bool:
Done

2023-09-20 10:50 UTC, merged