level 3 typing exercises
DanTheMain/typing_challenges pull request #3
Opened 2023-09-20 11:36 UTC by DanTheMain

2023-09-21 22:29 UTC, vppuzakov requested changes
👍 хорошо сделано c typeddict и callable
💡 только у маппинга осталось задать тип в первом задании

2023-09-21 22:29 UTC, vppuzakov commented on level_3/1.py
> +def get_transaction_amount(transaction_id: int, transactions_amounts_map: Mapping) -> decimal.Decimal:
🔴 у `Mapping` надо указать типы элементов ключа и значений
💡 посмотри на возвращаемый тип - он не только `Decimal`

2023-09-21 22:29 UTC, vppuzakov commented on level_3/2.py
> +def calculate_total_spent_for_user(user: UserType) -> int:
👍 все верно

2023-09-21 22:29 UTC, vppuzakov commented on level_3/2.py
> +class UserType(TypedDict):
👍 верно, лучше назвать `User`

2023-09-21 22:29 UTC, vppuzakov commented on level_3/3.py
> +def create_user(
👍 все верно

2023-09-22 09:49 UTC, DanTheMain commented on level_3/1.py
> +def get_transaction_amount(transaction_id: int, transactions_amounts_map: Mapping) -> decimal.Decimal:
Done

2023-09-22 09:49 UTC, DanTheMain commented on level_3/2.py
> +class UserType(TypedDict):
Done

2023-09-25 08:52 UTC, vppuzakov approved these changes
👍 хорошая работа, вмерживай

2023-09-25 08:52 UTC, vppuzakov commented on level_3/2.py
> +class User(TypedDict):
👍

2023-09-25 08:52 UTC, vppuzakov commented on level_3/1.py
> +        transaction_id: int, transactions_amounts_map: Mapping[int, decimal.Decimal]
👍 все верно

2023-09-27 17:52 UTC, merged